server:
  port: 8085
spring:
  application:
    name: sms-service
  rabbitmq:
    host: 192.168.43.253
    username: saber
    password: saber
    virtual-host: /saber
  redis:
    host: 192.168.43.253
ly:
  sms:
    accessKeyId: 
    accessKeySecret: 
    signName: 
    verifyCodeTemplate: 
