server:
  port: 8081
spring:
  application:
    name: item-service
  rabbitmq:
    host: 192.168.43.253
    username: saber
    password: saber
    virtual-host: /saber
    template:
      retry:
        enabled: true
        initial-interval: 10000ms
        max-interval: 30000ms
        multiplier: 2
      exchange: ly.item.exchange
    publisher-confirms: true
  datasource:
    url: jdbc:mysql://localhost:3306/people
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:10086/eureka
#  instance: #防止网络不稳定导致ip错乱，把ip写死
#    prefer-ip-address: true
#    ip-address: 127.0.0.1
mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl